### ISSUE TITLE
Rewrite Readme.md 

### ISSUE THREAD

**Issue by Welf06** [Welf06/Basic-Webpages#1]
Currently the Readme is really bland, It requires being rewritten in a creative way (including images and other graphics wherever possible). Things it should include:
->Introduction
->Maintainers
->Goal
->Showcase
->How to run it locally
->Contributors (Easy to add more entries in future)
An example to get you started https://github.com/vishal-lokare/AutoJoomer/blob/main/README.md

**Comment by GeniusNirmit** [comment]
Will this be a valid PR for Hacktober Fest?
If so then in am ready to take up...

**Comment by hackeramitkumar** [comment]
@Welf06 Can you please assign me this issue. I have written many README.md. I have successfully completed GSoC this year.

**Comment by Welf06** [comment]
Sure Amit
