### ISSUE TITLE
Changes in Landing Page

### ISSUE THREAD

**Issue by Welf06** [Welf06/Basic-Webpages#11]
>Change the text on the landing page, you can take the first para from readme and edit it (This is a repo of basic webpages, not basic web tools)
>The links in the tools section don't work, i.e doesn't take it to the respective subpage
>All the subpages haven't been included
>An image of the subpage can be used, instead of unsplash images

please  make sure the website doesn't break ✨

**Comment by aishwarya1735** [comment]
can this issue be assigned to me?

**Comment by Patil-Mandar** [comment]
Hey @Welf06, I would like to work on this issue.

**Comment by Welf06** [comment]
sorry guys, this has already been fixed by someone in their pr so its not required. 
Please feel free to raise other issues and work on it to improve the website ✨
