### ISSUE TITLE
connect web tool link to <tools.html>

### ISSUE THREAD

**Issue by GyanPrakashRaj** [Welf06/Basic-Webpages#13]
Sir @Welf06 
are you talking about this issue
In this issue i will change text of index page and i will active all webpages button to their directories....
if yes kindly assign this to me .. 🙏🏽 💯

**Comment by GyanPrakashRaj** [comment]
@Welf06 are you talking about this issue
if yes kindly assign this to me .. 🙏🏽 :

**Comment by Welf06** [comment]
@GyanPrakashRaj ok I will assign it to you, this repo contains basic webpages not tools 😭
Make sure to edit the text and the name in the homepage and link all the other subpages (there are like 6)

**Comment by Welf06** [comment]
I will merge your pr if it satisfies:
-  Appropriate changes to the text in the landing page in reference to README.md
- rename tools to pages/basic-webpates and same for tools.html
- Seperate the css and html in tools.html
- Make sure that you can actually redirect to other pages in tools.html
- Add comments in tools.html so its east for other people to add cards

**Comment by GyanPrakashRaj** [comment]
> I will merge your pr if it satisfies:
> 
> * Appropriate changes to the text in the landing page in reference to README.md
> * rename tools to pages/basic-webpates and same for tools.html
> * Seperate the css and html in tools.html
> * Make sure that you can actually redirect to other pages in tools.html
> * Add comments in tools.html so its east for other people to add cards

All changes are done, I hope I acted on your desired changes. https://github.com/Welf06/Basic-Webpages/pull/14
❤️

**Comment by Welf06** [comment]
Good job @GyanPrakashRaj ✨
