### ISSUE TITLE
Redesign of Landing Page

### ISSUE THREAD

**Issue by Welf06** [Welf06/Basic-Webpages#3]
You would have noticed the landing page of this repo is too bland without any css for the index.html file.
Your job is to change it ✨ 
-> Make the html changes to index.html, and don't create another HTML file unless absolutely necessary
-> Try to restrict the CSS to a single css file called main.css
-> Try to restrict the JS to a single js file called main.js
Apart from this, you are free to do as per your wish
Try to make it as awesome as you can!!

**Comment by GeniusNirmit** [comment]
Will this be a valid PR for Hacktober Fest?
If so then in am ready to take up...

**Comment by Welf06** [comment]
Yeah Nirmit, it would be a valid PR.

**Comment by sushmita2109** [comment]
Hey can i take up this task ??

**Comment by developerNd** [comment]
can you please assign this task to me?

**Comment by Welf06** [comment]
@sushmita2109 are you still interested in this issue?

**Comment by ved-rajpoot** [comment]
@Welf06 can u please assign this issue to me ?

**Comment by developerNd** [comment]
> can you please assign this task to me?


I'm waiting for your response..

**Comment by Welf06** [comment]
@developerNd you can take up this issue 
@ved-rajpoot since developerNd commented first, I wil assign it to him
