### ISSUE TITLE
A calender app

### ISSUE THREAD

**Issue by Welf06** [Welf06/Basic-Webpages#8]
> A simple calendar app with year view and month view
> A good UI/UX
Happy coding ✨

**Comment by GyanPrakashRaj** [comment]
hlw maintainer,
kindly assign this issue to me.

**Comment by Welf06** [comment]
@GyanPrakashRaj sure

**Comment by Naisargika1402** [comment]
Can I work on this too?

**Comment by GyanPrakashRaj** [comment]
> @GyanPrakashRaj sure

Hlw @Welf06 ,
i am very excited to tell you that i tried to enhance your UI of the page with a separate section of HTML,
i have "committed" on a branch named "gyanhacktober" for the UI pull request (#9 )
and add calendar issue#8 on my second commit 
kindly review my pull request and add (hacktober2022, hacktoberaccepted) as a level if you are merging.
thank you

**Comment by Naisargika1402** [comment]
@Welf06 Hello author,
My codes for this calendar app is almost ready. I have been working on this since I requested you for assigning this to me yesterday. This would by my first project contribution.
Can you please kindly assign this to me.

**Comment by Welf06** [comment]
@Naisargika1402 you can send a pr with the calender app directly, and if its good I will merge it in the repo and put the hacktoberfest-accepted label, so that it counts as a valid PR for hactoberfest.
I am closing this issue since GyanPrakashRaj already submitted a PR with the calender app

**Comment by Naisargika1402** [comment]
@Welf06 
Done! Kindly preview it.
